# Generated by Django 4.1.3 on 2022-12-17 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studenttype',
            name='user',
        ),
        migrations.AddField(
            model_name='studenttype',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studenttype',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='studenttype',
            name='student_type',
            field=models.CharField(max_length=50),
        ),
    ]
