# Generated by Django 4.1.3 on 2022-12-17 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0003_usertype_delete_studenttype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertype',
            name='user_id',
        ),
    ]
