# Generated by Django 4.1.3 on 2022-12-12 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz_Maker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='num_ques',
            field=models.IntegerField(default=3),
        ),
    ]
