# Generated by Django 4.1.3 on 2022-12-17 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz_Maker', '0002_quiz_num_ques'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='num_ques',
            field=models.IntegerField(default=5),
        ),
    ]
