# Generated by Django 4.1.3 on 2022-12-17 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz_Maker', '0003_alter_quiz_num_ques'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='order',
            field=models.IntegerField(null=True),
        ),
    ]
