# Generated by Django 4.1.3 on 2022-12-18 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz_Maker', '0004_answer_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='user_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
