# Generated by Django 4.1.3 on 2022-12-19 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz_Maker', '0005_quiz_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='quiz_pw',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
