# Generated by Django 4.1.3 on 2023-03-29 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz_Maker', '0007_question_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='submitted_answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='Quiz_Maker.answer'),
        ),
    ]
